
DROP TABLE IF EXISTS produkty;
DROP TABLE IF EXISTS class;

CREATE TABLE class (
    id VARCHAR(100) PRIMARY KEY,
    hlavna_kategoria VARCHAR(100) NOT NULL,
    nazov_tabulky VARCHAR(100) NOT NULL
);

INSERT INTO class (id, hlavna_kategoria, nazov_tabulky) VALUES
('rozvadzace', 'SK', 'Rozvádzače'),
('vybava_rozvadzacov', 'SK', 'Výbava rozvádzačov'),
('wifi_ap', 'SK', 'WiFi prístupové body'),
('switche', 'SK', 'Prepínače (switche)'),
('zalozne_zdroje', 'SK', 'Záložné zdroje'),
('zalozne_zdroje_extended', 'SK', 'Záložné zdroje – rozšírené'),
('battery_packy', 'SK', 'Batériové balíky'),
('kabelaz', 'SK', 'Štruktúrovaná kabeláž'),
('datove_zasuvky', 'SK', 'Dátové zásuvky'),
('podlahove_krabice', 'SK', 'Podlahové krabice'),
('ustredne', 'EZS', 'Ústredne'),
('radiove_moduly', 'EZS', 'Rádiové moduly'),
('komunikatory', 'EZS', 'Komunikátory'),
('rozhrania', 'EZS', 'Rozhrania'),
('pristupove_moduly_bezdrotove', 'EZS', 'Prístupové moduly – bezdrôtové'),
('pristupove_moduly', 'EZS', 'Prístupové moduly'),
('klavesnice_bezdrotove', 'EZS', 'Klávesnice – bezdrôtové'),
('klavesnice', 'EZS', 'Klávesnice'),
('citacky_pristupovych_kariet', 'EZS', 'Čítačky prístupových kariet'),
('ovladace', 'EZS', 'Ovládače'),
('identifikacne_prvky', 'EZS', 'Identifikačné prvky'),
('montazne_prislusenstvo', 'EZS', 'Montážne príslušenstvo'),
('sireny_vnutorne', 'EZS', 'Sirény – vnútorné'),
('sireny_vonkajsie', 'EZS', 'Sirény – vonkajšie'),
('pohybove_detektory_bezdrotove', 'EZS', 'Pohybové detektory – bezdrôtové'),
('pohybove_deterktory', 'EZS', 'Pohybové detektory'),
('plastove_detektory_bezdrotove', 'EZS', 'Plastové detektory – bezdrôtové'),
('magneticke_kontakty', 'EZS', 'Magnetické kontakty'),
('enviromentalne_detektory_bezdrotove', 'EZS', 'Environmentálne detektory – bezdrôtové'),
('enviromentalne_detektory', 'EZS', 'Environmentálne detektory'),
('prislusenstvo', 'EZS', 'Príslušenstvo'),
('vystupne_moduly', 'EZS', 'Výstupné moduly'),
('vstupne_moduly', 'EZS', 'Vstupné moduly'),
('rele', 'EZS', 'Relé moduly'),
('indikatory', 'EZS', 'Indikátory'),
('ip_kamery', 'CCTV', 'IP kamery'),
('nvr', 'CCTV', 'Záznamové zariadenia (NVR)'),
('uchytenie', 'CCTV', 'Uchytenie kamier');

CREATE TABLE produkty (
    id SERIAL PRIMARY KEY,
    produkt VARCHAR(100),
    jednotky VARCHAR(100),
    nakup_materialu DECIMAL(10,2),
    koeficient DECIMAL(10,2),
    cena_prace DECIMAL(10,2),
    dodavatel VARCHAR(100),
    odkaz TEXT,
    class_id VARCHAR(100) REFERENCES class(id)
);

INSERT INTO produkty (produkt, jednotky, nakup_materialu, koeficient, cena_prace, dodavatel, odkaz, class_id) VALUES
('Rozvádzač 24U', 'ks', 150.00, 1.2, 45.00, 'ABB', 'https://example.com/rozvadzace/1', 'rozvadzace'),
('Rozvádzač 42U', 'ks', 250.00, 1.3, 60.00, 'Legrand', 'https://example.com/rozvadzace/2', 'rozvadzace'),
('Police do rozvádzača', 'ks', 20.00, 1.0, 5.00, 'Eaton', 'https://example.com/vybava_rozvadzacov/3', 'vybava_rozvadzacov'),
('Ventilátorový panel', 'ks', 35.00, 1.1, 7.00, 'Eaton', 'https://example.com/vybava_rozvadzacov/4', 'vybava_rozvadzacov'),
('UniFi AP AC Lite', 'ks', 75.00, 1.2, 10.00, 'Ubiquiti', 'https://example.com/wifi_ap/5', 'wifi_ap'),
('Mikrotik cAP', 'ks', 55.00, 1.1, 8.00, 'Mikrotik', 'https://example.com/wifi_ap/6', 'wifi_ap'),
('Cisco SG350', 'ks', 180.00, 1.2, 20.00, 'Cisco', 'https://example.com/switche/7', 'switche'),
('TP-Link SG108', 'ks', 45.00, 1.0, 5.00, 'TP-Link', 'https://example.com/switche/8', 'switche'),
('APC Back-UPS', 'ks', 100.00, 1.0, 15.00, 'APC', 'https://example.com/zalozne_zdroje/9', 'zalozne_zdroje'),
('Eaton UPS', 'ks', 110.00, 1.1, 18.00, 'Eaton', 'https://example.com/zalozne_zdroje/10', 'zalozne_zdroje'),
('Ústredňa Galaxy', 'ks', 300.00, 1.1, 60.00, 'Honeywell', 'https://example.com/ustredne/11', 'ustredne'),
('Ústredňa DSC', 'ks', 280.00, 1.0, 55.00, 'DSC', 'https://example.com/ustredne/12', 'ustredne'),
('Hikvision IP Kamera', 'ks', 220.00, 1.0, 40.00, 'Hikvision', 'https://example.com/ip_kamery/13', 'ip_kamery'),
('Dahua Bullet Kamera', 'ks', 240.00, 1.1, 42.00, 'Dahua', 'https://example.com/ip_kamery/14', 'ip_kamery'),
('NVR 4-kanál', 'ks', 180.00, 1.1, 35.00, 'Hikvision', 'https://example.com/nvr/15', 'nvr'),
('NVR 8-kanál', 'ks', 220.00, 1.2, 40.00, 'Dahua', 'https://example.com/nvr/16', 'nvr'),
('Produkt 17', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/zalozne_zdroje_extended/17', 'zalozne_zdroje_extended'),
('Produkt 18', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/zalozne_zdroje_extended/18', 'zalozne_zdroje_extended'),
('Produkt 19', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/battery_packy/19', 'battery_packy'),
('Produkt 20', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/battery_packy/20', 'battery_packy'),
('Produkt 21', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/kabelaz/21', 'kabelaz'),
('Produkt 22', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/kabelaz/22', 'kabelaz'),
('Produkt 23', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/datove_zasuvky/23', 'datove_zasuvky'),
('Produkt 24', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/datove_zasuvky/24', 'datove_zasuvky'),
('Produkt 25', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/podlahove_krabice/25', 'podlahove_krabice'),
('Produkt 26', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/podlahove_krabice/26', 'podlahove_krabice'),
('Produkt 27', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/radiove_moduly/27', 'radiove_moduly'),
('Produkt 28', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/radiove_moduly/28', 'radiove_moduly'),
('Produkt 29', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/komunikatory/29', 'komunikatory'),
('Produkt 30', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/komunikatory/30', 'komunikatory'),
('Produkt 31', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/rozhrania/31', 'rozhrania'),
('Produkt 32', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/rozhrania/32', 'rozhrania'),
('Produkt 33', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pristupove_moduly_bezdrotove/33', 'pristupove_moduly_bezdrotove'),
('Produkt 34', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pristupove_moduly_bezdrotove/34', 'pristupove_moduly_bezdrotove'),
('Produkt 35', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pristupove_moduly/35', 'pristupove_moduly'),
('Produkt 36', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pristupove_moduly/36', 'pristupove_moduly'),
('Produkt 37', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/klavesnice_bezdrotove/37', 'klavesnice_bezdrotove'),
('Produkt 38', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/klavesnice_bezdrotove/38', 'klavesnice_bezdrotove'),
('Produkt 39', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/klavesnice/39', 'klavesnice'),
('Produkt 40', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/klavesnice/40', 'klavesnice'),
('Produkt 41', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/citacky_pristupovych_kariet/41', 'citacky_pristupovych_kariet'),
('Produkt 42', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/citacky_pristupovych_kariet/42', 'citacky_pristupovych_kariet'),
('Produkt 43', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/ovladace/43', 'ovladace'),
('Produkt 44', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/ovladace/44', 'ovladace'),
('Produkt 45', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/identifikacne_prvky/45', 'identifikacne_prvky'),
('Produkt 46', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/identifikacne_prvky/46', 'identifikacne_prvky'),
('Produkt 47', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/montazne_prislusenstvo/47', 'montazne_prislusenstvo'),
('Produkt 48', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/montazne_prislusenstvo/48', 'montazne_prislusenstvo'),
('Produkt 49', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/sireny_vnutorne/49', 'sireny_vnutorne'),
('Produkt 50', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/sireny_vnutorne/50', 'sireny_vnutorne'),
('Produkt 51', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/sireny_vonkajsie/51', 'sireny_vonkajsie'),
('Produkt 52', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/sireny_vonkajsie/52', 'sireny_vonkajsie'),
('Produkt 53', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pohybove_detektory_bezdrotove/53', 'pohybove_detektory_bezdrotove'),
('Produkt 54', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pohybove_detektory_bezdrotove/54', 'pohybove_detektory_bezdrotove'),
('Produkt 55', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pohybove_deterktory/55', 'pohybove_deterktory'),
('Produkt 56', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/pohybove_deterktory/56', 'pohybove_deterktory'),
('Produkt 57', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/plastove_detektory_bezdrotove/57', 'plastove_detektory_bezdrotove'),
('Produkt 58', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/plastove_detektory_bezdrotove/58', 'plastove_detektory_bezdrotove'),
('Produkt 59', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/magneticke_kontakty/59', 'magneticke_kontakty'),
('Produkt 60', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/magneticke_kontakty/60', 'magneticke_kontakty'),
('Produkt 61', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/enviromentalne_detektory_bezdrotove/61', 'enviromentalne_detektory_bezdrotove'),
('Produkt 62', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/enviromentalne_detektory_bezdrotove/62', 'enviromentalne_detektory_bezdrotove'),
('Produkt 63', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/enviromentalne_detektory/63', 'enviromentalne_detektory'),
('Produkt 64', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/enviromentalne_detektory/64', 'enviromentalne_detektory'),
('Produkt 65', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/prislusenstvo/65', 'prislusenstvo'),
('Produkt 66', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/prislusenstvo/66', 'prislusenstvo'),
('Produkt 67', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/vystupne_moduly/67', 'vystupne_moduly'),
('Produkt 68', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/vystupne_moduly/68', 'vystupne_moduly'),
('Produkt 69', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/vstupne_moduly/69', 'vstupne_moduly'),
('Produkt 70', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/vstupne_moduly/70', 'vstupne_moduly'),
('Produkt 71', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/rele/71', 'rele'),
('Produkt 72', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/rele/72', 'rele'),
('Produkt 73', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/indikatory/73', 'indikatory'),
('Produkt 74', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/indikatory/74', 'indikatory'),
('Produkt 75', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/uchytenie/75', 'uchytenie'),
('Produkt 76', 'ks', 100.00, 1.0, 15.00, 'Generic', 'https://example.com/uchytenie/76', 'uchytenie');